name = "realm"
title = "MongoDB Realm"

intersphinx = [
  "https://www.mongodb.com/docs/manual/objects.inv",
  "https://www.mongodb.com/docs/atlas/objects.inv",
  "https://www.mongodb.com/docs/atlas/app-services/objects.inv"
]

# These are the pages that open when you click on them (instead of just being containers)
toc_landing_pages = [
  # Tutorial
  "/tutorial",
  # Cloud
  "/cloud",
  "/authentication",
  "/authentication/providers",
  "/mongodb",
  "/graphql",
  "/functions",
  "/functions/mongodb",
  "/services",
  "/services/http",
  "/services/twilio",
  "/hosting",
  "/values-and-secrets",
  "/manage-apps/deploy",
  "/logs",
  "/manage-apps/configure/config",
  "/manage-apps/configure/export-realm-app",
  "/manage-apps/secure",
  "/schemas",
  "/rules",
  "/endpoints",
  # SDKs
  "/sdk",
  "/sdk/java",
  "/sdk/java/api",
  "/sdk/swift",
  "/sdk/node",
  "/sdk/react-native",
  "/sdk/kotlin",
  "/sdk/web",
  "/sdk/dotnet",
  "/sdk/flutter",
  "/sdk/swift/examples/work-with-users",
  # Old SDKs
  "/android",
  "/ios",
  "/node",
  "/react-native",
  "/web",
  "/dotnet",
  # CLI
  "/cli",
  "/cli/realm-cli-accessList",
  "/cli/realm-cli-apps",
  "/cli/realm-cli-function",
  "/cli/realm-cli-logs",
  "/cli/realm-cli-schema",
  "/cli/realm-cli-secrets",
  "/cli/realm-cli-users",
  # Other
  "/studio",
  "/release-notes"
]

[substitutions]
atlas = "Atlas"

[constants]
realm = "realm"
realms = "realms"
client-database = "Realm Database"
client-db-short = "Realm"
atlas = "MongoDB Atlas"
atlas-short = "Atlas"
compass = "MongoDB Compass"
compass-short = "Compass"
charts = "MongoDB Charts"
charts-short = "Charts"
service = "MongoDB Realm" # product (backend + sdks)
service-short = "Realm" # use as shorthand, AND as a prefix for features
backend = "MongoDB Realm"
backend-short = "Realm"
sync = "Realm Sync"
sync-short = "Sync" # feature/product name, NOT verb
backend-schema = "Realm Schema"
frontend-schema = "Realm Object Model"
cli-bin = ":binary:`realm-cli`" # binary -- DO NOT USE IN LINKS! Will break them.
cli = "Realm CLI"
ui = "Realm UI"
app = "Realm app"
leftnav = "left navigation menu"
admin-api-page = "/admin/api/v3/#"
base-url = "https://www.mongodb.com/docs/realm"
kotlin-sdk-version = "0.11.1"
kotlinx-coroutines-version = "1.6.0-native-mt"
kotlin-sync-prefix = "library-sync/-realm%20-kotlin%20-multiplatform%20-s-d-k%20-%20-sync/"
kotlin-local-prefix = "library-base/-realm%20-kotlin%20-multiplatform%20-s-d-k/"
java-sdk-version = "10.10.1"
max-graphql-resolvers = "ten"
max-graphql-relationship-depth = "five"
log-retention-time = "10 days"
encrypted-interprocess-sharing-error-message = "Encrypted interprocess sharing is currently unsupported."
