name = "realm"
title = "MongoDB Realm"

intersphinx = [
  "https://docs.mongodb.com/manual/objects.inv",
  "https://docs.atlas.mongodb.com/objects.inv"
]

# These are the pages that open when you click on them (instead of just being containers)
toc_landing_pages = [
  # Tutorial
  "/tutorial",
  # Cloud
  "/cloud",
  "/authentication",
  "/authentication/providers",
  "/mongodb",
  "/sync",
  "/graphql",
  "/functions",
  "/services",
  "/services/http",
  "/services/twilio",
  "/hosting",
  "/values-and-secrets",
  "/manage-apps/deploy",
  "/logs",
  "/manage-apps/configure/config",
  "/manage-apps/configure/export-realm-app",
  "/manage-apps/secure",
  "/schemas",
  "/rules",
  # SDKs
  "/sdk",
  "/sdk/android",
  "/sdk/ios",
  "/sdk/node",
  "/sdk/react-native",
  "/sdk/kotlin-multiplatform",
  "/sdk/web",
  "/sdk/dotnet",
  "/sdk/flutter",
  "/sdk/ios/examples/work-with-users",
  # Old SDKs
  "/android",
  "/ios",
  "/node",
  "/react-native",
  "/web",
  "/dotnet",
  # CLI
  "/cli",
  "/cli/realm-cli-accessList",
  "/cli/realm-cli-apps",
  "/cli/realm-cli-function",
  "/cli/realm-cli-logs",
  "/cli/realm-cli-schema",
  "/cli/realm-cli-secrets",
  "/cli/realm-cli-users",
  # Other
  "/studio",
  "/release-notes"
]

[substitutions]
atlas = "Atlas"

[constants]
realm = "realm"
realms = "realms"
client-database = "Realm Database"
client-db-short = "Realm"
atlas = "MongoDB Atlas"
atlas-short = "Atlas"
compass = "MongoDB Compass"
compass-short = "Compass"
charts = "MongoDB Charts"
charts-short = "Charts"
service = "MongoDB Realm" # product (backend + sdks)
service-short = "Realm" # use as shorthand, AND as a prefix for features
backend = "MongoDB Realm"
backend-short = "Realm"
sync = "Realm Sync"
sync-short = "Sync" # feature/product name, NOT verb
backend-schema = "Realm Schema"
frontend-schema = "Realm Object Model"
cli-bin = "``realm-cli``" # binary -- DO NOT USE IN LINKS! Will break them.
cli = "Realm CLI"
ui = "Realm UI"
app = "Realm app"
leftnav = "left navigation menu"
admin-api-page = "/admin/api/v3/#"
base-url = "https://docs.mongodb.com/realm"
kotlin-sdk-version = "0.7.0"
android-sdk-version = "10.8.1"
