name = "realm"

[constants]
package-name-org = "docs-realm"
realm = "Realm"
realms = "Realms"
client-database = "Realm Database"
atlas = "MongoDB Atlas"
atlas-short = "Atlas"
backend = "MongoDB Realm"
backend-short = "Realm"
service = "MongoDB Realm"
service-short = "Realm"
sync = "Realm Sync"
sync-short = "Sync"
sync-protocol = "Realm Sync Protocol"
sync-protocol-short = "Sync Protocol"
instance = "Realm app"
instances = "Realm apps"
instance-short = "app"
instances-short = "apps"
schema = "Realm Data Model"
backend-schema = "Realm Schema"
frontend-schema = "Realm Object Model"
cli = "realm-cli"
ui = "Realm UI"
function = "Realm Function"
functions = "Realm Functions"
function-short = "Function"
functions-short = "Functions"
trigger = "Realm Trigger"
triggers = "Realm Triggers"
trigger-short = "Trigger"
triggers-short = "Triggers"
rule = "Realm rule"
rules = "Realm rules"
rule-short = "Rule"
rules-short = "Rules"
secret = "Realm secret"
secrets = "Realm secrets"
secret-short = "Secret"
secrets-short = "Secrets"
value = "Realm value"
values = "Realm values"
value-short = "Value"
values-short = "Values"
compass = "MongoDB Compass"
sdk = "Realm SDK"
