name = "realm"
title = "MongoDB Realm"

intersphinx = [
  "https://docs.mongodb.com/manual/objects.inv",
  "https://docs.atlas.mongodb.com/objects.inv"
]

# These are the pages that open when you click on them (instead of just being containers)
toc_landing_pages = [
  # Tutorial
  "/tutorial",
  # Cloud
  "/authentication",
  "/mongodb",
  "/sync",
  "/graphql",
  "/functions",
  "/triggers",
  "/services",
  "/hosting",
  "/values-and-secrets",
  "/deploy",
  "/logs",
  # SDKs
  "/android",
  "/ios",
  "/node",
  "/react-native",
  "/web"
]

[substitutions]
atlas = "Atlas"

[constants]
realm = "realm"
realms = "realms"
client-database = "Realm Database"
atlas = "MongoDB Atlas"
atlas-short = "Atlas"
compass = "MongoDB Compass"
compass-short = "Compass"
charts = "MongoDB Charts"
charts-short = "Charts"
service = "MongoDB Realm" # product (backend + sdks)
service-short = "Realm" # use as shorthand, AND as a prefix for features
backend = "MongoDB Realm"
backend-short = "Realm"
sync = "Realm Sync"
sync-short = "Sync" # feature/product name, NOT verb
backend-schema = "Realm Schema"
frontend-schema = "Realm Object Model"
cli-bin = "``realm-cli``" # binary -- DO NOT USE IN LINKS! Will break them.
cli = "Realm CLI"
ui = "Realm UI"
app = "Realm app"
leftnav = "left navigation menu"
