name = "realm"
title = "Realm"

intersphinx = [
  "https://www.mongodb.com/docs/manual/objects.inv",
  "https://www.mongodb.com/docs/atlas/objects.inv",
  "https://www.mongodb.com/docs/atlas/app-services/objects.inv"
]

# These are the pages that open when you click on them (instead of just being containers)
toc_landing_pages = [
  # Tutorial
  "/tutorial",
  # SDKs
  "/sdk",
  "/sdk/cpp",
  "/sdk/cpp/application-services",
  "/sdk/cpp/manage-users",
  "/sdk/cpp/sync",
  "/sdk/java",
  "/sdk/java/api",
  "/sdk/java/app-services",
  "/sdk/java/crud",
  "/sdk/java/manage-users",
  "/sdk/java/model-data",
  "/sdk/java/realm-files",
  "/sdk/java/sync",
  "/sdk/swift",
  "/sdk/swift/application-services",
  "/sdk/swift/crud",
  "/sdk/swift/model-data",
  "/sdk/swift/realm-files",
  "/sdk/swift/swiftui",
  "/sdk/swift/sync",
  "/sdk/swift/work-with-users",
  "/sdk/node",
  "/sdk/node/app-services",
  "/sdk/node/crud",
  "/sdk/node/manage-users",
  "/sdk/node/model-data",
  "/sdk/node/realm-files",
  "/sdk/node/sync",
  "/sdk/react-native",
  "/sdk/react-native/app-services",
  "/sdk/react-native/crud",
  "/sdk/react-native/manage-users",
  "/sdk/react-native/model-data",
  "/sdk/react-native/realm-files",
  "/sdk/react-native/sync-data",
  "/sdk/kotlin",
  "/sdk/kotlin/app-services",
  "/sdk/kotlin/users",
  "/sdk/kotlin/realm-database",
  "/sdk/kotlin/realm-database/schemas",
  "/sdk/kotlin/realm-database/realm-files",
  "/sdk/kotlin/realm-database/write-transactions",
  "/sdk/kotlin/sync",
  "/sdk/web",
  "/sdk/dotnet",
  "/sdk/dotnet/work-with-users",
  "/sdk/dotnet/application-services",
  "/sdk/dotnet/unity",  
  "/sdk/dotnet/sync",
  "/sdk/flutter",
  "/sdk/swift/examples/work-with-users",
  "/sdk/flutter/realm-database/model-data",
  "/sdk/flutter/users",
  "/sdk/flutter/realm-database",
  "/sdk/flutter/app-services",
  "/sdk/flutter/sync",
  "sdk/flutter/realm-database/realm-files",
  # Old SDKs
  "/android",
  "/ios",
  "/node",
  "/react-native",
  "/web",
  "/web/users",
  "/web/atlas-app-services",
  "/dotnet",
  # Other
  "/studio",
  "/release-notes"
]

[substitutions]
atlas = "Atlas"

[constants]
admin-api-page = "/admin/api/v3/#"
base-url = "https://www.mongodb.com/docs/realm"
cpp-prefix = "https://www.mongodb.com/docs/realm-sdks/cpp/latest"
kotlin-sdk-version = "1.7.0"
kotlinx-coroutines-version = "1.6.4"
kotlin-sync-prefix = "https://www.mongodb.com/docs/realm-sdks/kotlin/latest/library-sync/-realm%20-kotlin%20-s-d-k%20-%20-sync/"
kotlin-local-prefix = "https://www.mongodb.com/docs/realm-sdks/kotlin/latest/library-base/-realm%20-kotlin%20-s-d-k/"
java-sdk-version = "10.11.1"
max-graphql-resolvers = "ten"
max-graphql-relationship-depth = "five"
name-char-limit = "57"
log-retention-time = "10 days"
sync = "Atlas Device Sync"
sync-short = "Device Sync" # feature/product name, NOT verb
