title: Upload Your Built Application to Realm
ref: upload-your-built-application-to-realm
content: |
  Single-page applications render in a single, specific HTML file,
  typically ``/index.html``. The file should include the necessary
  JavaScript code to wire up and render your application, either inline
  in a ``<script>`` tag or imported from an external file. You'll also
  need to host any resources that you don't intend to access through a
  CDN.
  
  When you are ready to host your SPA, run your application's build
  script and then :doc:`upload the build folder
  </hosting/upload-content-to-realm>` to {+service+}.
---
title: Configure Realm to Serve Your Application
ref: configure-realm-to-serve-your-application
content: |
  Once you've started hosting your application files, you can
  immediately access your SPA by requesting the root HTML file directly.
  However, a request to any path other than the root file will return a
  404. This can break the expected behavior of a SPA that uses a
  client-side router or otherwise relies on the URL path.
  
  To configure {+service-short+} to serve the SPA's root page for all requests:
  
  1. Navigate to the :guilabel:`Hosting` page in the {+ui+} and then
     click the :guilabel:`Settings` tab.
  
  2. Ensure that you have not specified a custom 404 page. If custom 404
     is enabled, click the trash can icon (:icon-fa5:`trash-alt`) next
     to the specified 404 page.
  
  3. Next to :guilabel:`Single Page Application`, click :guilabel:`Choose
     File`. Choose the root HTML file for your SPA and then click
     :guilabel:`Select`.

  4. Click :guilabel:`Save`.

  .. cssclass:: bordered-figure
  .. figure:: /images/enable-spa-realm-ui.png
...
