title: Export Your Realm Application
ref: export-your-application
content: |
  To add metadata attributes to hosted files with :doc:`realm-cli
  </deploy/realm-cli-reference>` you need to export an
  :ref:`application directory <application-directory>` for your
  application.

  You can :doc:`export </deploy/export-realm-app>` your application from
  the :guilabel:`Export` tab of the :guilabel:`Settings` page in the
  {+ui+}, or by running the following command from an authenticated
  instance of :doc:`realm-cli </deploy/realm-cli-reference>`:

  .. code-block:: shell

     realm-cli export --app-id=<App ID>
---
title: Add Attributes to the Metadata Configuration File
ref: add-attributes-to-the-metadata-configuration-file
content: |
  The metadata for all hosted files associated with your application is
  configured by an array of metadata attribute definition objects that
  you define in a file named :ref:`metadata.json
  <hosting-metadata-json>` in your application's ``hosting``
  subdirectory.

  {+service+} will automatically infer and assign a ``Content-Type`` to every
  file you upload. If you you want to override the default
  ``Content-Type`` or specify additional :doc:`metadata attributes
  </hosting/file-metadata-attributes>` for a file, add an entry to
  :ref:`metadata.json <hosting-metadata-json>` for the file and
  attributes that you want to configure. Each file's entry should be a
  document with the following form:

  .. include:: /hosting/includes/metadata-config-json.rst

  .. note::

     If you include an entry in ``metadata.json`` for a file that does
     not exist, you will not be able to import your changes. Ensure that
     only hosted files are represented in ``metadata.json``.
---
title: Import the File Metadata Configuration
ref: import-the-file-metadata-configuration
content: |
  Once you have added all the metadata attributes you want to configure
  to ``metadata.json``, you can import the application directory to
  actually update the associated file metadata.

  Navigate to the root of the application directory and run the
  following command:

  .. code-block:: shell

     realm-cli import --include-hosting
...
