title: Navigate to the Collection Rules Screen
ref: navigate-to-the-mongodb-rules-screen
level: 4
content: |
  You can edit collection rules in Advanced Mode from the MongoDB rules
  screen in the {+ui+}. To get to the rules screen for a collection,
  click :guilabel:`Rules` beneath :guilabel:`Data Access` in the
  {+leftnav+} and then select the collection from the list.
  
  .. figure:: /images/collection-rules-basic-mode.png
     :alt: Basic mode rules editor in the {+ui+}

---
title: Convert to Advanced Mode
ref: convert-to-advanced-mode
level: 4
content: |
  Click :guilabel:`Advanced Mode` in the top right corner of the
  collection rules interface. The UI will switch an editor that shows a
  preview of the underlying Advanced Mode rule configuration document.
  Click :guilabel:`Convert to Advanced Mode` and then click
  :guilabel:`Convert Rules` to confirm.
  
  .. figure:: /images/collection-rules-convert-to-advanced-mode.png
     :alt: Advanced Mode preview in the {+ui+} collection rules editor.

---
title: Define the Collection Rules
ref: define-the-collection-rules
level: 4
content: |
  Once you have converted the collection to Advanced Mode you can edit
  the underlying configuration document. Collection rule configuration
  documents have the following form:

  .. code-block:: json
     
     {
       "roles": [
         <Role Configuration>,
         ...
       ],
       "filters": [
         <Filter Configuration>,
         ...
       ],
       "schema": {
         "properties": {
           "<Field Name>": <Schema Document>,
           ...
         }
       }
     }

  .. list-table::
    :widths: 30 70
    :header-rows: 1

    * - Field
      - Description

    * - ``roles``
      - An array of :ref:`Query Role configuration documents <query-role-config>` that each define a single role's :guilabel:`Apply When` condition and associated CRUD permissions.
      
        .. important::
            
            {+service-short+} evaluates roles for each query in the order that
            they're defined. Ensure that each role configuration
            document's array index matches its desired position in the
            evaluation order.

    * - ``filters``
      - An array of :ref:`Query Filter configuration documents <query-filter-config>` that each define a filter on the collection.
      
    * - ``schema``
      - A :ref:`Document Schema <document-schema-config>` that configures the shape and contents of all documents in the collection.

        .. note::
            
            The root of all collection schemas must be an :ref:`object
            schema document <schema-type-objects>`. You can embed other
            :ref:`schema types <schema-types>` inside the ``properties``
            field of the root schema.

---
title: Save the Updated Collection Rules
ref: save-the-updated-collection-rules
level: 4
content: |
  Once you have finished editing the collection rules, click
  :guilabel:`Save`. {+service+} will immediately begin using the new rule
  configuration you defined for all incoming queries on the collection.
