name: myapp
description: A simple command-line application using Realm Dart SDK.

publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  realm_dart:
    path: ./realm-dart
  test: ^1.20.1

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.1.2
