name: myapp
description: A simple command-line application using Realm Dart SDK.

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  realm_dart: 0.4.0+beta
  path: ^1.8.2
  test: ^1.20.1

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.1.2
