name: .NET Core CI Realm Example App

on:
  pull_request:
    paths:
      - 'examples/dotnet/**'

jobs:
  build:
    name: Run .NET Example App Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.404
    - name: Install dependencies
      run: cd examples/dotnet && dotnet restore
    - name: Build
      run: cd examples/dotnet && dotnet build --configuration Debug --no-restore
    - name: Test
      run: cd examples/dotnet && dotnet test --no-restore --verbosity normal
