name: iOS CI Realm Example App

on:
  pull_request:
    paths:
      - "examples/ios/**"

jobs:
  build:
    name: Run iOS Example App Tests
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "13.3.0"
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          cd examples/ios
          xcodebuild build-for-testing -scheme "Test Examples" -destination "platform=iOS Simulator,name=iPhone 13 Pro"
      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          cd examples/ios
          xcodebuild test-without-building -scheme "Test Examples" -destination "platform=iOS Simulator,name=iPhone 13 Pro"
