name: Node.js SDK v12 CI Tests

on:
  pull_request:
    paths:
      - "examples/node/v12/**"

jobs:
  run-jest-tests:
    name: Run Node.js SDK v12 Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: examples/node/v12
        shell: bash
        run: npm install
      - name: Annotate failed tests
        run: npx github-actions-ctrf test-result.json
        if: always()
      - name: Test JavaScript
        shell: bash
        working-directory: examples/node/v12
        run: npm run test:js
      - name: Test TypeScript
        shell: bash
        working-directory: examples/node/v12
        run: npm run test:ts
      - name: Publish Test Summary Results
        run: npx github-actions-ctrf test-result.json
