name: Readability

on: pull_request

jobs:
  scoreText:
    name: Parse text, score text, and report scores on PR.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo.
        uses: actions/checkout@v3
      - name: Get changed files.
        id: changed-files
        uses: tj-actions/changed-files@v23.2
      - name: List changed files (debugging log statement).
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Checkout docdoctor repo.
        uses: actions/checkout@v3
        with:
          repository: dacharyc/docdoctor
          ref: "readability"
          path: "docdoctor"
      - name: Display workspace directory structure (debugging log statement)
        run: |
          ls $GITHUB_WORKSPACE
      - name: Install Node.js.
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Parse text from rST.
        run: |
          pushd docdoctor && npm i && npm run build && popd
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            node ./docdoctor getReadabilityText "$file"
          done
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          # We need Python version 3.5 or greater for rglob.
          python-version: "3.6"
          architecture: "x64"
      - name: Install textstat
        run: pip install textstat
      - name: Create scores directory.
        run: mkdir -p scores
      - name: Calculate Readability score.
        run: python $GITHUB_WORKSPACE/Calculate_Readability_Score.py
      - name: Upload score results
        uses: actions/upload-artifact@v3
        with:
          name: scores
          path: scores/scores.md
